### ISSUE TITLE
Button doesn't do anything on `building` page.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#12]
![screenshot from 2016-12-12 12-09-33](https://cloud.githubusercontent.com/assets/1911594/21097230/e2e40b4e-c063-11e6-8511-f98bdc74c702.png)
This button doesn't do anything.

**Comment by iliyaM** [comment]
this button should reveal more article if there are more than 3. 
in page building there are only 3. 
if you want to check behavior go to /organic
