### ISSUE TITLE
No active menu indication.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#13]
Main menu needs to have indicated on which page user is currently on. As it is right now only way to know this is to remember it. And with icons being different
![screenshot from 2016-12-12 12-10-12](https://cloud.githubusercontent.com/assets/1911594/21097271/1254b036-c064-11e6-9771-bf69d2a75df1.png)
, this is impossible.

**Comment by iliyaM** [comment]
done
