### ISSUE TITLE
Proper content formatting.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#15]
![screenshot from 2016-12-12 12-15-39](https://cloud.githubusercontent.com/assets/1911594/21097444/bf12a5d0-c064-11e6-8a96-8c00896b76dd.png)
In Markdown lists need to be separated by one empty line for them to be properly formatted in HTML.

**Comment by iliyaM** [comment]
seperated between each list item. still the same result
![screenshot from 2016-12-12 14-25-04](https://cloud.githubusercontent.com/assets/20294485/21099435/d92a5e6a-c076-11e6-90c4-72459dd60226.png)
