### ISSUE TITLE
Icon sizes on contact form are broken.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#17]
![screenshot from 2016-12-12 12-31-53](https://cloud.githubusercontent.com/assets/1911594/21097881/059e26ee-c067-11e6-8113-f059780a09e7.png)
Icons are round in design but they are cut out on the side.

**Comment by iliyaM** [comment]
no idea how to fix that and why that happens

**Comment by iliyaM** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1056784
