### ISSUE TITLE
Missing content on Next-site

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Next-Site#18]
1. Clients phone nubmer
2. href to links in footer
3. Real information in contact page (phone nuber, facebook, youtube)
4. Sub title in contact page

**Comment by MeanEYE** [comment]
@iliyaM do we have this information? Site is already up to my knowledge. If so, close the issue.

**Comment by talovdat** [comment]
Just went through the site with client and that issue was never mentioned.
please close issue its no longer relevant .
