### ISSUE TITLE
Contact form field type shouldn't be number.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#2]
![screenshot from 2016-12-12 11-44-24](https://cloud.githubusercontent.com/assets/1911594/21096483/5837d50a-c060-11e6-8384-4a3ed92ce07e.png)
As seen on screen shot type for phone number field is set as `number`. This is not a valid type for phone numbers as it accepts only whole numbers. Entering 054 is not a valid entry as it beings with zero. This needs to be fixed and set to regular text with phone number format if they want to enforce it.

**Comment by iliyaM** [comment]
fixed
