### ISSUE TITLE
Home pace spelling mistake

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Next-Site#26]
At the home page, H2, there is a missing letter. 

![image](https://user-images.githubusercontent.com/26923359/27172550-4ccfccdc-51be-11e7-91d4-6c35816841f5.png)

**Comment by talovdat** [comment]
Did not got fixed. 
Still missing the same letter.

**Comment by MeanEYE** [comment]
@talovdat this is probably due to site not being deployed. Site is not hosted with us so we can't easily deploy all the time as it requires manual file comparison. We are waiting for all the issues to be reported and fixed before I make an endeavor to upload it.
