### ISSUE TITLE
Contact us page missing icon

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Next-Site#30]
There is a missing icon inside the contact us page.
Map icon.

![image](https://user-images.githubusercontent.com/26923359/27173879-bf18af76-51c2-11e7-89bf-d3c7476ca995.png)

**Comment by iliyaM** [comment]
Locally works...live site shows all of them instead of location icon. 
Site-sprite name is correctly written icon-location.
Any suggestions @MeanEYE

**Comment by MeanEYE** [comment]
Learn how to write file names with extension.

**Comment by iliyaM** [comment]
10 push ups for this one
