### ISSUE TITLE
Site Map

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Next-Site#32]
Please create a site map.

**Comment by MeanEYE** [comment]
A bit late for this. Why was this reported this late?

**Comment by talovdat** [comment]
Client asked what is up with the site map, is there anything I can help with to make that happen by the end of the week?

**Comment by talovdat** [comment]
@MeanEYE , regarded to your request for "priority for pages for sitemap".
It goes:
home page
services categories
articles 
'contact us' page

**Comment by MeanEYE** [comment]
Should I include elements in categories and articles?

**Comment by talovdat** [comment]
What does it mean?

**Comment by MeanEYE** [comment]
They have inner pages for services and articles.
Do I include those as well.

**Comment by talovdat** [comment]
Yes, between articles and contact us page.

_Sent from my Samsung SM-J710F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
