### ISSUE TITLE
Worng page layout 

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Next-Site#33]
Wrong page layout on /funding page.

**Comment by MeanEYE** [comment]
Issue originates from [here](https://github.com/Way2CU/Next-Site/commit/4d23cc7c47e2c3dc981b6e0a7db58d1fcb112252#diff-fcb67a5ee5d7a6ef0e369eb42c8a93d0R384). @iliyaM made a change without testing.

**Comment by MeanEYE** [comment]
This issue appeared again for some reason. We need to make sure it's fixed. Check the original site and compare if your fixes are even applied.
