### ISSUE TITLE
Mobile - Menu doesn't work

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Next-Site#35]
On the mobile version, the menu does not work.
Tested on Android and IOS.
Chrome and Safari browsers.
![image](https://user-images.githubusercontent.com/26923359/33706025-457d5aec-db3b-11e7-9fe5-ceb0c92411cf.png)

**Comment by MeanEYE** [comment]
@VladimirWebDev please double check.

**Comment by VladimirWebDev** [comment]
I removed reason why menu was not working..

**Comment by MeanEYE** [comment]
Which was?

**Comment by VladimirWebDev** [comment]
Overriding rule defined in header_mobile.less which put nav.mobile_menu on right absolut position on 150%. Rules defined for .mobile_menu class in mobile_menu.css will be applied but transform: translate3D(100,0,0) will not put nav in position viewable by user..

**Comment by MeanEYE** [comment]
Okay. So it's a valid issue.
