### ISSUE TITLE
Redesign floating menu.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#4]
Design and implementation of floating menu needs to change. I don't want to _EVER_ again see click handled drop down menu. Also, Michael should come up with less ugly icon.

![screenshot from 2016-12-12 11-47-57](https://cloud.githubusercontent.com/assets/1911594/21096607/f6be915a-c060-11e6-8a00-b0b25b2872eb.png)

**Comment by iliyaM** [comment]
how will it work on tablet if i change it to click?

**Comment by iliyaM** [comment]
behavior done. waiting for svg icon

**Comment by MeanEYE** [comment]
@iliyaM updates on this?

**Comment by iliyaM** [comment]
![screenshot from 2017-01-08 10-59-43](https://cloud.githubusercontent.com/assets/20294485/21748603/a0f7f2de-d591-11e6-9304-ded2076ecd84.png)

**Comment by MeanEYE** [comment]
What?
