### ISSUE TITLE
Header underlines need to be changed either in color or design.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#5]
![screenshot from 2016-12-12 12-00-34](https://cloud.githubusercontent.com/assets/1911594/21096974/9c602c1c-c062-11e6-8d42-21d9c8a73a00.png)
![screenshot from 2016-12-12 11-49-25](https://cloud.githubusercontent.com/assets/1911594/21096975/9c6056b0-c062-11e6-9216-d6eceb48108f.png)
As it is right now header underline makes it look like input field causing additional confusion.

**Comment by iliyaM** [comment]
The designer needs to be in on this one.
