### ISSUE TITLE
Spacing between elements needs to be fixed.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#6]
![screenshot from 2016-12-12 12-02-10](https://cloud.githubusercontent.com/assets/1911594/21097023/dc5835da-c062-11e6-95b9-b1f9ca8694f9.png)
This kind of spacing implies button is a part of bottom element, instead of top one. Spacing needs to be fixed in such a way to keep make the button feel as it belongs to the top.

**Comment by iliyaM** [comment]
fixed
