### ISSUE TITLE
Main JavaScript tries to create page control on other pages than home.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Next-Site#8]
![screenshot from 2016-12-12 12-04-48](https://cloud.githubusercontent.com/assets/1911594/21097109/41c6de08-c063-11e6-8ab5-7611f11eddd8.png)
Right now it looks like `main.js` is creating `PageControl` on all pages and causing console to be filled with errors. These errors need to be fixed.

**Comment by iliyaM** [comment]
fixed
